# Generated by Django 5.1.2 on 2024-11-20 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_product_expirydate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='ProductPlace',
            field=models.CharField(max_length=12, unique=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='QRNumber',
            field=models.CharField(max_length=25, unique=True),
        ),
    ]
