# Generated by Django 5.1.2 on 2024-11-21 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_alter_product_productplace_alter_product_qrnumber'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='AICode',
            field=models.CharField(default='code', max_length=12),
        ),
        migrations.AlterField(
            model_name='product',
            name='NumberOfViews',
            field=models.IntegerField(default=0),
        ),
    ]
