# Generated by Django 5.1.2 on 2025-04-18 15:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("product", "0003_alter_product_productavailable_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="ModifiedBy",
        ),
        migrations.AddField(
            model_name="product",
            name="modifier_content_type",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="contenttypes.contenttype",
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="modifier_object_id",
            field=models.PositiveIntegerField(null=True),
        ),
    ]
