# Generated by Django 5.1.2 on 2025-06-11 02:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("product", "0004_remove_product_modifiedby_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="ProductPlace",
            field=models.CharField(max_length=25, unique=True),
        ),
    ]
