# Generated by Django 5.1.2 on 2025-04-17 14:20

import datetime
import django.db.models.deletion
import uuid
import worker.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("worker", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Admin",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("UserName", models.CharField(max_length=100, unique=True)),
                ("Password", models.CharField(blank=True, max_length=1024)),
                ("Name", models.CharField(max_length=100)),
                ("Phone", models.CharField(blank=True, max_length=11, null=True)),
                ("Email", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "AdminImage",
                    models.ImageField(
                        default="adminPhotos/default/adminImage.png",
                        upload_to="adminPhotos/",
                    ),
                ),
                ("IsSuperAdmin", models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name="Job",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("JobName", models.CharField(max_length=100, unique=True)),
                ("JobDescription", models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="AdminToken",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "token",
                    models.CharField(default=uuid.uuid4, max_length=512, unique=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "expires_at",
                    models.DateTimeField(
                        default=datetime.datetime(
                            2025,
                            4,
                            18,
                            14,
                            20,
                            34,
                            221509,
                            tzinfo=datetime.timezone.utc,
                        )
                    ),
                ),
                (
                    "admin",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="worker.admin"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Worker",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("WorkerUserName", models.CharField(max_length=100, unique=True)),
                ("WorkerPassword", models.CharField(blank=True, max_length=1024)),
                ("WorkerName", models.CharField(max_length=100)),
                ("WorkerPhone", models.CharField(blank=True, max_length=11, null=True)),
                (
                    "WorkerEmail",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "WorkerAddress",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("WorkerSalary", models.IntegerField(default=0)),
                (
                    "WorkerImage",
                    models.ImageField(
                        default="workerPhotos/default/workerImage.png",
                        upload_to=worker.models.worker_directory_path,
                    ),
                ),
                ("IsSupervisor", models.BooleanField(default=False)),
                (
                    "WorkerJobTitle",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="workers",
                        to="worker.job",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="WorkerPermission",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("can_add_products", models.BooleanField(default=False)),
                ("can_edit_products", models.BooleanField(default=False)),
                ("can_delete_products", models.BooleanField(default=False)),
                (
                    "JobName",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="permissions",
                        to="worker.job",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="WorkerToken",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "token",
                    models.CharField(default=uuid.uuid4, max_length=512, unique=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "expires_at",
                    models.DateTimeField(
                        default=datetime.datetime(
                            2025,
                            4,
                            18,
                            14,
                            20,
                            34,
                            220269,
                            tzinfo=datetime.timezone.utc,
                        )
                    ),
                ),
                (
                    "worker",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="worker.worker"
                    ),
                ),
            ],
        ),
    ]
