# Generated by Django 5.1.2 on 2024-11-11 11:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('worker', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='worker',
            old_name='workerUserName',
            new_name='WorkerUserName',
        ),
    ]
