# Generated by Django 5.1.2 on 2024-11-12 18:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('worker', '0003_workertoken'),
    ]

    operations = [
        migrations.AlterField(
            model_name='worker',
            name='WorkerJobTitle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='WorkerJobTitle', to='worker.job'),
        ),
    ]
