# Generated by Django 5.1.2 on 2024-11-12 20:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('worker', '0005_alter_worker_workerjobtitle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workertoken',
            name='worker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='worker_auth_tokens', to='worker.worker'),
        ),
    ]
