# Generated by Django 5.1.2 on 2024-11-12 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('worker', '0007_alter_worker_workeraddress_alter_worker_workeremail_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='worker',
            name='WorkerPassword',
            field=models.CharField(max_length=1024, null=True),
        ),
    ]
