# Generated by Django 5.1.2 on 2025-04-22 18:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("worker", "0007_alter_admintoken_expires_at_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="admintoken",
            name="expires_at",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2025, 4, 23, 18, 42, 47, 279867, tzinfo=datetime.timezone.utc
                )
            ),
        ),
        migrations.AlterField(
            model_name="workertoken",
            name="expires_at",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2025, 4, 23, 18, 42, 47, 279867, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
