# Generated by Django 5.1.2 on 2024-11-12 21:27

import functions.worker.worker
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('worker', '0008_alter_worker_workerpassword'),
    ]

    operations = [
        migrations.AlterField(
            model_name='worker',
            name='WorkerPassword',
            field=models.CharField(blank=True, default=functions.worker.worker.password, max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='worker',
            name='WorkerUserName',
            field=models.CharField(max_length=100),
        ),
    ]
