# Generated by Django 5.1.2 on 2024-11-12 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('worker', '0009_alter_worker_workerpassword_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='worker',
            name='WorkerPassword',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='worker',
            name='WorkerUserName',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
