# Generated by Django 5.1.2 on 2024-11-12 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('worker', '0010_alter_worker_workerpassword_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='JobName',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
