# Generated by Django 5.1.2 on 2024-11-19 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('worker', '0011_alter_job_jobname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='worker',
            name='WorkerSalary',
            field=models.IntegerField(default=0),
        ),
    ]
