# Generated by Django 5.1.2 on 2025-03-14 23:24

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("worker", "0011_alter_job_jobname"),
        ("worker", "0012_alter_worker_workersalary"),
    ]

    operations = []
