# Generated by Django 5.1.2 on 2025-03-15 00:01

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("worker", "0014_admin_rename_created_workertoken_created_at_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="WorkerToken",
        ),
    ]
