# Generated by Django 5.1.2 on 2025-03-15 00:08

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("worker", "0015_delete_workertoken"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="admintoken",
            name="admin",
        ),
        migrations.DeleteModel(
            name="Admin",
        ),
        migrations.DeleteModel(
            name="AdminToken",
        ),
    ]
