# Generated by Django 5.1.2 on 2025-03-15 00:08

import django.db.models.deletion
import functions.worker.worker
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("worker", "0016_remove_admintoken_admin_delete_admin_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Admin",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("UserName", models.CharField(max_length=100, unique=True)),
                ("Password", models.CharField(blank=True, max_length=1024, null=True)),
                ("Name", models.CharField(max_length=100)),
                ("Phone", models.CharField(max_length=11, null=True)),
                ("Email", models.CharField(max_length=100, null=True)),
                (
                    "WorkerImage",
                    models.ImageField(
                        default="workerPhotos/default/workerImage.png",
                        upload_to=functions.worker.worker.worker_directory_path,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="AdminToken",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "token",
                    models.CharField(default=uuid.uuid4, max_length=512, unique=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("expires_at", models.DateTimeField()),
                (
                    "admin",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="worker.admin"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="WorkerToken",
            fields=[
                (
                    "id",
                    models.BigAutoField(default=1, primary_key=True, serialize=False),
                ),
                (
                    "token",
                    models.CharField(default=uuid.uuid4, max_length=512, unique=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("expires_at", models.DateTimeField(default=None, null=True)),
                (
                    "worker",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="worker.worker"
                    ),
                ),
            ],
        ),
    ]
