# Generated by Django 5.1.2 on 2025-03-15 01:05

import worker.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("worker", "0017_admin_admintoken_workertoken"),
    ]

    operations = [
        migrations.AddField(
            model_name="admin",
            name="groups",
            field=models.ManyToManyField(blank=True, related_name="+", to="auth.group"),
        ),
        migrations.AddField(
            model_name="admin",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="admin",
            name="is_staff",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="admin",
            name="is_superuser",
            field=models.BooleanField(
                default=False,
                help_text="Designates that this user has all permissions without explicitly assigning them.",
                verbose_name="superuser status",
            ),
        ),
        migrations.AddField(
            model_name="admin",
            name="last_login",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="last login"
            ),
        ),
        migrations.AddField(
            model_name="admin",
            name="user_permissions",
            field=models.ManyToManyField(
                blank=True, related_name="+", to="auth.permission"
            ),
        ),
        migrations.AddField(
            model_name="worker",
            name="groups",
            field=models.ManyToManyField(blank=True, related_name="+", to="auth.group"),
        ),
        migrations.AddField(
            model_name="worker",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="worker",
            name="is_staff",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="worker",
            name="is_superuser",
            field=models.BooleanField(
                default=False,
                help_text="Designates that this user has all permissions without explicitly assigning them.",
                verbose_name="superuser status",
            ),
        ),
        migrations.AddField(
            model_name="worker",
            name="last_login",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="last login"
            ),
        ),
        migrations.AddField(
            model_name="worker",
            name="password",
            field=models.CharField(
                default="shehab", max_length=128, verbose_name="password"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="worker",
            name="user_permissions",
            field=models.ManyToManyField(
                blank=True, related_name="+", to="auth.permission"
            ),
        ),
        migrations.AlterField(
            model_name="admin",
            name="Email",
            field=models.EmailField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="admin",
            name="Password",
            field=models.CharField(default="", max_length=1024),
        ),
        migrations.AlterField(
            model_name="admin",
            name="WorkerImage",
            field=models.ImageField(
                default="workerPhotos/default/workerImage.png",
                upload_to=worker.models.worker_directory_path,
            ),
        ),
        migrations.AlterField(
            model_name="worker",
            name="WorkerEmail",
            field=models.EmailField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="worker",
            name="WorkerImage",
            field=models.ImageField(
                default="workerPhotos/default/workerImage.png",
                upload_to=worker.models.worker_directory_path,
            ),
        ),
        migrations.AlterField(
            model_name="workertoken",
            name="expires_at",
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name="workertoken",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
