# Generated by Django 5.1.2 on 2025-03-15 01:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("worker", "0018_admin_groups_admin_is_active_admin_is_staff_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="admin",
            name="Password",
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
    ]
