# Generated by Django 5.1.2 on 2025-03-15 01:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("worker", "0019_admin_password"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="admin",
            name="groups",
        ),
        migrations.RemoveField(
            model_name="admin",
            name="is_active",
        ),
        migrations.RemoveField(
            model_name="admin",
            name="is_staff",
        ),
        migrations.RemoveField(
            model_name="admin",
            name="is_superuser",
        ),
        migrations.RemoveField(
            model_name="admin",
            name="last_login",
        ),
        migrations.RemoveField(
            model_name="admin",
            name="user_permissions",
        ),
        migrations.RemoveField(
            model_name="worker",
            name="groups",
        ),
        migrations.RemoveField(
            model_name="worker",
            name="is_active",
        ),
        migrations.RemoveField(
            model_name="worker",
            name="is_staff",
        ),
        migrations.RemoveField(
            model_name="worker",
            name="is_superuser",
        ),
        migrations.RemoveField(
            model_name="worker",
            name="last_login",
        ),
        migrations.RemoveField(
            model_name="worker",
            name="password",
        ),
        migrations.RemoveField(
            model_name="worker",
            name="user_permissions",
        ),
        migrations.AlterField(
            model_name="admin",
            name="Email",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="worker",
            name="WorkerEmail",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="workertoken",
            name="expires_at",
            field=models.DateTimeField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name="workertoken",
            name="id",
            field=models.BigAutoField(default=1, primary_key=True, serialize=False),
        ),
    ]
