# Generated by Django 5.1.2 on 2025-03-15 02:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("worker", "0020_remove_admin_groups_remove_admin_is_active_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="admintoken",
            name="role",
            field=models.CharField(
                choices=[
                    ("super_admin", "Super Admin"),
                    ("manager", "Manager"),
                    ("Administrator", "administrator"),
                    ("Admin", "admin"),
                ],
                default="manager",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="workertoken",
            name="role",
            field=models.CharField(
                choices=[
                    ("basic_worker", "Basic Worker"),
                    ("supervisor", "Supervisor"),
                    ("worker", "Worker"),
                ],
                default="basic_worker",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="workertoken",
            name="expires_at",
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name="workertoken",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
