# Generated by Django 5.1.2 on 2025-03-15 03:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("worker", "0022_admin_issuperadmin"),
    ]

    operations = [
        migrations.AddField(
            model_name="worker",
            name="IsSupervisor",
            field=models.BooleanField(default=False),
        ),
    ]
