# Generated by Django 5.1.2 on 2025-03-16 20:21

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("worker", "0023_worker_issupervisor"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="admin",
            name="WorkerImage",
        ),
        migrations.RemoveField(
            model_name="admintoken",
            name="role",
        ),
        migrations.RemoveField(
            model_name="workertoken",
            name="role",
        ),
        migrations.AddField(
            model_name="admin",
            name="AdminImage",
            field=models.ImageField(
                default="adminPhotos/default/adminImage.png", upload_to="adminPhotos/"
            ),
        ),
        migrations.AlterField(
            model_name="admin",
            name="Email",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="admin",
            name="Password",
            field=models.CharField(blank=True, max_length=1024),
        ),
        migrations.AlterField(
            model_name="admin",
            name="Phone",
            field=models.CharField(blank=True, max_length=11, null=True),
        ),
        migrations.AlterField(
            model_name="admintoken",
            name="expires_at",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2025, 3, 17, 20, 21, 40, 971565, tzinfo=datetime.timezone.utc
                )
            ),
        ),
        migrations.AlterField(
            model_name="job",
            name="JobDescription",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="worker",
            name="WorkerAddress",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="worker",
            name="WorkerEmail",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="worker",
            name="WorkerJobTitle",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="workers",
                to="worker.job",
            ),
        ),
        migrations.AlterField(
            model_name="worker",
            name="WorkerPassword",
            field=models.CharField(blank=True, max_length=1024),
        ),
        migrations.AlterField(
            model_name="worker",
            name="WorkerPhone",
            field=models.CharField(blank=True, max_length=11, null=True),
        ),
        migrations.AlterField(
            model_name="workertoken",
            name="expires_at",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2025, 3, 17, 20, 21, 40, 971565, tzinfo=datetime.timezone.utc
                )
            ),
        ),
        migrations.CreateModel(
            name="WorkerPermission",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("can_add_products", models.BooleanField(default=False)),
                ("can_edit_products", models.BooleanField(default=False)),
                ("can_delete_products", models.BooleanField(default=False)),
                (
                    "job",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="permissions",
                        to="worker.job",
                    ),
                ),
            ],
        ),
    ]
