# Generated by Django 5.1.2 on 2025-03-17 00:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("worker", "0024_remove_admin_workerimage_remove_admintoken_role_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="admintoken",
            name="expires_at",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2025, 3, 18, 0, 42, 57, 465259, tzinfo=datetime.timezone.utc
                )
            ),
        ),
        migrations.AlterField(
            model_name="workertoken",
            name="expires_at",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2025, 3, 18, 0, 42, 57, 464259, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
