# Generated by Django 5.1.2 on 2025-03-17 12:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("worker", "0027_alter_admintoken_expires_at_alter_job_jobname_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="admintoken",
            name="expires_at",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2025, 3, 18, 12, 8, 31, 340405, tzinfo=datetime.timezone.utc
                )
            ),
        ),
        migrations.AlterField(
            model_name="job",
            name="JobName",
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name="workertoken",
            name="expires_at",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2025, 3, 18, 12, 8, 31, 339406, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
