# Generated by Django 5.1.2 on 2025-03-17 12:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("worker", "0028_alter_admintoken_expires_at_alter_job_jobname_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="workerpermission",
            old_name="job",
            new_name="JobName",
        ),
        migrations.AlterField(
            model_name="admintoken",
            name="expires_at",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2025, 3, 18, 12, 29, 26, 489638, tzinfo=datetime.timezone.utc
                )
            ),
        ),
        migrations.AlterField(
            model_name="workertoken",
            name="expires_at",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2025, 3, 18, 12, 29, 26, 488660, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
