# Generated by Django 5.1.2 on 2025-03-17 12:56

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("worker", "0029_rename_job_workerpermission_jobname_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="admintoken",
            name="expires_at",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2025, 3, 18, 12, 56, 19, 577274, tzinfo=datetime.timezone.utc
                )
            ),
        ),
        migrations.AlterField(
            model_name="workerpermission",
            name="JobName",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="permissions",
                to="worker.job",
            ),
        ),
        migrations.AlterField(
            model_name="workertoken",
            name="expires_at",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2025, 3, 18, 12, 56, 19, 576275, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
