# Generated by Django 5.1.2 on 2025-03-22 21:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("worker", "0036_alter_admintoken_expires_at_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="admintoken",
            name="expires_at",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2025, 3, 23, 21, 32, 42, 646909, tzinfo=datetime.timezone.utc
                )
            ),
        ),
        migrations.AlterField(
            model_name="workertoken",
            name="expires_at",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2025, 3, 23, 21, 32, 42, 646909, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
