# Generated by Django 5.1.2 on 2025-04-17 20:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("User", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="client",
            name="is_verified",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="client",
            name="verification_code",
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
    ]
