# Generated by Django 5.1.2 on 2024-10-22 18:59

import datetime
import functions.user.client
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('User', '0002_delete_client'),
    ]

    operations = [
        migrations.CreateModel(
            name='client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clientUserName', models.CharField(max_length=50)),
                ('clientPassword', models.CharField(max_length=500)),
                ('clientFirstName', models.CharField(default='YourFirstName', max_length=50)),
                ('clientLastName', models.CharField(default='YourLastName', max_length=50)),
                ('clientEmail', models.CharField(default='<EMAIL>', max_length=100)),
                ('clientPhone', models.IntegerField(default='01234567890', max_length=11)),
                ('clientBirthdate', models.DateField(default=datetime.date.today)),
                ('clientMoney', models.IntegerField(default=0)),
                ('clientPoints', models.IntegerField(default=0)),
                ('clientImage', models.ImageField(default='clientPhotos/default/clientImage.png', upload_to=functions.user.client.client_directory_path)),
            ],
        ),
    ]
