# Generated by Django 5.1.2 on 2024-10-22 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0003_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='clientGender',
            field=models.CharField(choices=[('male', 'male'), ('female', 'female'), ('other', 'other')], default='male', max_length=10),
        ),
        migrations.AlterField(
            model_name='client',
            name='clientPhone',
            field=models.CharField(default='01234567890', max_length=11),
        ),
    ]
