# Generated by Django 5.1.2 on 2024-10-22 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0004_client_clientgender_alter_client_clientphone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='clientUserName',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
