# Generated by Django 5.1.2 on 2024-11-08 22:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0005_alter_client_clientusername'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='clientUserName',
            field=models.CharField(max_length=50),
        ),
        migrations.CreateModel(
            name='ClientToken',
            fields=[
                ('key', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='auth_tokens', to='User.client')),
            ],
        ),
    ]
