# Generated by Django 5.1.2 on 2024-11-08 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0006_alter_client_clientusername_clienttoken'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='clientUserName',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
