# Generated by Django 5.1.2 on 2025-03-12 21:36

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("User", "0007_alter_client_clientusername"),
    ]

    operations = [
        migrations.CreateModel(
            name="VirtualCart",
            fields=[
                ("VCId", models.AutoField(primary_key=True, serialize=False)),
                ("VCQuantity", models.FloatField(default=0.0)),
                ("VCTotalPrice", models.FloatField(default=0.0)),
                ("VCTotalWeight", models.FloatField(default=0.0)),
                ("VCQRCode", models.CharField(default="", max_length=11)),
                ("VCPINcode", models.CharField(default="", max_length=6)),
                ("VCStatus", models.BooleanField(default=False)),
                ("VCDate", models.DateTimeField(auto_now_add=True)),
                (
                    "Client",
                    models.ForeignKey(
                        on_delete=models.SET("deleted user"),
                        related_name="UserName",
                        to="User.client",
                    ),
                ),
            ],
        ),
    ]
