# Generated by Django 5.1.2 on 2025-03-13 12:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cart", "0001_initial"),
        ("product", "0004_alter_product_aicode_alter_product_numberofviews"),
    ]

    operations = [
        migrations.CreateModel(
            name="VirtualCartItems",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Quantity", models.FloatField(default=0.0)),
                ("Price", models.FloatField(default=0.0)),
                ("Weight", models.FloatField(default=0.0)),
                ("ProductName", models.CharField(default="", max_length=100)),
                ("CategoryName", models.CharField(default="", max_length=100)),
                (
                    "Product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="product.product",
                    ),
                ),
                (
                    "VCItimeID",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="cart.virtualcart",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["Product", "VCItimeID"],
                        name="cart_virtua_Product_335015_idx",
                    )
                ],
                "unique_together": {("Product", "VCItimeID")},
            },
        ),
    ]
