# Generated by Django 5.1.2 on 2025-04-22 18:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cart", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="purchasedcartitem",
            name="purchasedAt",
            field=models.DateTimeField(default=datetime.timezone),
        ),
    ]
