# Generated by Django 5.1.2 on 2025-03-13 18:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cart", "0002_virtualcartitems"),
    ]

    operations = [
        migrations.CreateModel(
            name="EasyCart",
            fields=[
                ("EasyCartID", models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
    ]
