# Generated by Django 5.1.2 on 2025-04-22 18:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cart", "0003_alter_purchasedcartitem_purchasedat"),
    ]

    operations = [
        migrations.AlterField(
            model_name="purchasedcart",
            name="createdAt",
            field=models.DateTimeField(default=datetime.timezone),
        ),
    ]
