# Generated by Django 5.1.2 on 2025-03-14 18:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cart", "0003_easycart"),
    ]

    operations = [
        migrations.AddField(
            model_name="easycart",
            name="ECStatus",
            field=models.BooleanField(default=False),
        ),
    ]
