# Generated by Django 5.1.2 on 2025-05-04 18:54

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cart", "0004_alter_purchasedcart_createdat"),
    ]

    operations = [
        migrations.AlterField(
            model_name="purchasedcart",
            name="createdAt",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name="purchasedcartitem",
            name="purchasedAt",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
