# Generated by Django 5.1.2 on 2025-03-22 21:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("User", "0009_rename_isclinet_client_isclient"),
        ("cart", "0004_easycart_ecstatus"),
        ("product", "0005_wishlist"),
    ]

    operations = [
        migrations.RenameField(
            model_name="virtualcart",
            old_name="VCDate",
            new_name="created_at",
        ),
        migrations.RenameField(
            model_name="virtualcart",
            old_name="VCQuantity",
            new_name="total_price",
        ),
        migrations.RenameField(
            model_name="virtualcart",
            old_name="VCTotalPrice",
            new_name="total_weight",
        ),
        migrations.RemoveField(
            model_name="easycart",
            name="ECStatus",
        ),
        migrations.RemoveField(
            model_name="easycart",
            name="EasyCartID",
        ),
        migrations.RemoveField(
            model_name="virtualcart",
            name="Client",
        ),
        migrations.RemoveField(
            model_name="virtualcart",
            name="VCId",
        ),
        migrations.RemoveField(
            model_name="virtualcart",
            name="VCPINcode",
        ),
        migrations.RemoveField(
            model_name="virtualcart",
            name="VCQRCode",
        ),
        migrations.RemoveField(
            model_name="virtualcart",
            name="VCStatus",
        ),
        migrations.RemoveField(
            model_name="virtualcart",
            name="VCTotalWeight",
        ),
        migrations.AddField(
            model_name="easycart",
            name="battery_level",
            field=models.FloatField(default=100.0),
        ),
        migrations.AddField(
            model_name="easycart",
            name="cart_id",
            field=models.CharField(default=1, max_length=50, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="easycart",
            name="clientUser",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="User.client",
            ),
        ),
        migrations.AddField(
            model_name="easycart",
            name="id",
            field=models.BigAutoField(
                auto_created=True,
                default=1,
                primary_key=True,
                serialize=False,
                verbose_name="ID",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="easycart",
            name="last_updated",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="easycart",
            name="location",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="easycart",
            name="status",
            field=models.CharField(
                choices=[
                    ("available", "Available"),
                    ("in_use", "In Use"),
                    ("abandoned", "Abandoned"),
                ],
                default="available",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="easycart",
            name="total_items",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="easycart",
            name="total_weight",
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name="virtualcart",
            name="clientUser",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="v_carts",
                to="User.client",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="virtualcart",
            name="id",
            field=models.BigAutoField(
                auto_created=True,
                default=0,
                primary_key=True,
                serialize=False,
                verbose_name="ID",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="virtualcart",
            name="qr_code",
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
        migrations.AddField(
            model_name="virtualcart",
            name="total_items",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="virtualcart",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.CreateModel(
            name="EasyCartItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantity", models.IntegerField(default=1)),
                ("weight", models.FloatField(default=0.0)),
                ("total_price", models.FloatField(default=0.0)),
                (
                    "cart",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="cart.easycart",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="product.product",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="VirtualCartItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantity", models.IntegerField(default=1)),
                ("total_price", models.FloatField(default=0.0)),
                ("weight", models.FloatField(default=0.0)),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="product.product",
                    ),
                ),
                (
                    "v_cart",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="cart.virtualcart",
                    ),
                ),
            ],
        ),
        migrations.DeleteModel(
            name="VirtualCartItems",
        ),
    ]
