# Generated by Django 5.1.2 on 2025-03-22 21:34

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("cart", "0005_rename_vcdate_virtualcart_created_at_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="easycartitem",
            name="cart",
        ),
        migrations.RemoveField(
            model_name="easycartitem",
            name="product",
        ),
        migrations.RemoveField(
            model_name="virtualcart",
            name="clientUser",
        ),
        migrations.RemoveField(
            model_name="virtualcartitem",
            name="v_cart",
        ),
        migrations.RemoveField(
            model_name="virtualcartitem",
            name="product",
        ),
        migrations.DeleteModel(
            name="EasyCart",
        ),
        migrations.DeleteModel(
            name="EasyCartItem",
        ),
        migrations.DeleteModel(
            name="VirtualCart",
        ),
        migrations.DeleteModel(
            name="VirtualCartItem",
        ),
    ]
