# Generated by Django 5.1.2 on 2025-03-22 21:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("User", "0009_rename_isclinet_client_isclient"),
        ("cart", "0006_remove_easycartitem_cart_remove_easycartitem_product_and_more"),
        ("product", "0005_wishlist"),
    ]

    operations = [
        migrations.CreateModel(
            name="EasyCart",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("cart_id", models.CharField(max_length=50, unique=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("available", "Available"),
                            ("in_use", "In Use"),
                            ("abandoned", "Abandoned"),
                        ],
                        default="available",
                        max_length=20,
                    ),
                ),
                ("location", models.CharField(blank=True, max_length=100, null=True)),
                ("battery_level", models.FloatField(default=100.0)),
                ("total_weight", models.FloatField(default=0.0)),
                ("total_items", models.IntegerField(default=0)),
                ("last_updated", models.DateTimeField(auto_now=True)),
                (
                    "clientUser",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="User.client",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="EasyCartItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantity", models.IntegerField(default=1)),
                ("weight", models.FloatField(default=0.0)),
                ("total_price", models.FloatField(default=0.0)),
                (
                    "cart",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="cart.easycart",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="product.product",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="VirtualCart",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "qr_code",
                    models.CharField(blank=True, max_length=50, null=True, unique=True),
                ),
                ("total_weight", models.FloatField(default=0.0)),
                ("total_price", models.FloatField(default=0.0)),
                ("total_items", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "clientUser",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="v_carts",
                        to="User.client",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="VirtualCartItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantity", models.IntegerField(default=1)),
                ("total_price", models.FloatField(default=0.0)),
                ("weight", models.FloatField(default=0.0)),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="product.product",
                    ),
                ),
                (
                    "v_cart",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="cart.virtualcart",
                    ),
                ),
            ],
        ),
    ]
