# Generated by Django 5.1.2 on 2025-04-03 01:11

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("User", "0009_rename_isclinet_client_isclient"),
        ("cart", "0008_remove_easycartitem_cart_remove_easycartitem_product_and_more"),
        ("product", "0005_wishlist"),
    ]

    operations = [
        migrations.CreateModel(
            name="EasyCart",
            fields=[
                (
                    "cartId",
                    models.CharField(
                        max_length=50, primary_key=True, serialize=False, unique=True
                    ),
                ),
                (
                    "cartStatus",
                    models.CharField(
                        choices=[
                            ("ready", "Ready"),
                            ("in_use", "In Use"),
                            ("error", "Error"),
                        ],
                        default="ready",
                        max_length=20,
                    ),
                ),
                (
                    "batteryPercentage",
                    models.IntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ]
                    ),
                ),
                ("location", models.CharField(max_length=50)),
                ("lastUsedAt", models.DateTimeField(blank=True, null=True)),
                ("createdAt", models.DateTimeField(auto_now_add=True)),
                ("updatedAt", models.DateTimeField(auto_now=True)),
                (
                    "lastUsedBy",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="User.client",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="EasyCartVirtualCart",
            fields=[
                (
                    "cartId",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("isActive", models.BooleanField(default=True)),
                ("totalPrice", models.FloatField(default=0.0)),
                ("totalWeight", models.FloatField(default=0.0)),
                ("totalQuantity", models.IntegerField(default=0)),
                ("createdAt", models.DateTimeField(auto_now_add=True)),
                ("updatedAt", models.DateTimeField(auto_now=True)),
                (
                    "client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="User.client"
                    ),
                ),
                (
                    "easyCart",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="cart.easycart"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PurchasedCart",
            fields=[
                (
                    "cartId",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("createdAt", models.DateTimeField(auto_now_add=True)),
                ("totalAmount", models.FloatField()),
                ("totalWeight", models.FloatField()),
                ("totalQuantity", models.IntegerField()),
                ("paymentMethod", models.CharField(max_length=50)),
                (
                    "nfcTransactionId",
                    models.CharField(
                        blank=True, max_length=100, null=True, unique=True
                    ),
                ),
                (
                    "client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="User.client"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PurchasedCartItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "quantity",
                    models.IntegerField(
                        validators=[django.core.validators.MinValueValidator(1)]
                    ),
                ),
                ("priceAtPurchase", models.FloatField()),
                ("purchasedAt", models.DateTimeField(auto_now_add=True)),
                (
                    "cart",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="cart.purchasedcart",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="product.product",
                        to_field="QRNumber",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="VirtualCart",
            fields=[
                (
                    "cartId",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "qrCode",
                    models.CharField(
                        blank=True, max_length=100, null=True, unique=True
                    ),
                ),
                ("isActive", models.BooleanField(default=True)),
                ("totalPrice", models.FloatField(default=0.0)),
                ("totalWeight", models.FloatField(default=0.0)),
                ("totalQuantity", models.IntegerField(default=0)),
                ("createdAt", models.DateTimeField(auto_now_add=True)),
                ("updatedAt", models.DateTimeField(auto_now=True)),
                (
                    "client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="User.client"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="EasyCartVirtualCartItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "quantity",
                    models.IntegerField(
                        validators=[django.core.validators.MinValueValidator(1)]
                    ),
                ),
                ("addedAt", models.DateTimeField(auto_now_add=True)),
                ("updatedAt", models.DateTimeField(auto_now=True)),
                (
                    "cart",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="cart.easycartvirtualcart",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="product.product",
                        to_field="QRNumber",
                    ),
                ),
            ],
            options={
                "unique_together": {("cart", "product")},
            },
        ),
        migrations.CreateModel(
            name="VirtualCartItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "quantity",
                    models.IntegerField(
                        validators=[django.core.validators.MinValueValidator(1)]
                    ),
                ),
                ("addedAt", models.DateTimeField(auto_now_add=True)),
                ("updatedAt", models.DateTimeField(auto_now=True)),
                (
                    "cart",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="cart.virtualcart",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="product.product",
                        to_field="QRNumber",
                    ),
                ),
            ],
            options={
                "unique_together": {("cart", "product")},
            },
        ),
    ]
