# Generated by Django 5.1.2 on 2025-04-03 11:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cart", "0009_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="easycart",
            name="cartId",
            field=models.CharField(
                editable=False,
                max_length=50,
                primary_key=True,
                serialize=False,
                unique=True,
            ),
        ),
    ]
