# Generated by Django 5.1.2 on 2025-04-03 11:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cart", "0010_alter_easycart_cartid"),
    ]

    operations = [
        migrations.AddField(
            model_name="easycart",
            name="VirtualCart",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="cart.virtualcart",
            ),
        ),
        migrations.AddField(
            model_name="easycart",
            name="beginningWeight",
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name="easycart",
            name="numberOfItems",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="easycart",
            name="weight",
            field=models.FloatField(default=0),
        ),
    ]
