# Generated by Django 5.1.2 on 2025-04-14 01:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cart", "0012_alter_easycart_weight"),
    ]

    operations = [
        migrations.AddField(
            model_name="easycart",
            name="lastMaintenanceTime",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
